openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample Zoom User Management API
  description: |-
    Sample API for a specific use case to manage zoom users.

tags:
  - name: Sample API
    description: Can be used in flows to mimic a 3rd party system.

components:
  parameters:
    email:
      required: true
      name: email
      in: query
      description: User's email address
      schema:
        type: string

  schemas:
    "Response":
      type: object
      description: Response object.
      properties:
        user:
          type: string
        message:
          type: string

  responses:
    "200":
      description: Success.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
    "400":
      description: Account is not inactive or basic.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
    "404":
      description: User not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
    "500":
      description: API error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
paths:
  "/user":
    get:
      tags:
        - Sample API
      summary: Update a user
      parameters:
        - $ref: "#/components/parameters/email"
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"
